### ISSUE TITLE
[fis3-hook-commonjs] require('/xxxx/folder');  无效。

### ISSUE THREAD

**Issue by worry127722** [fex-team/fis3-hook-commonjs#1]
问题描述：require('/xxxx/folder'); 这个 folder 同时又是  packages 里面的某个目录，无法识别。
期望：使用 packages 里面 main 来查找依赖的文件

**Comment by oxUnd** [comment]
这个其实我觉着没啥用，不要加了。

**Comment by 2betop** [comment]
已经修复！
