### ISSUE TITLE
应当升级一下 source-map 版本，解决 TypeError: Cannot read property 'substr' of undefined 问题

### ISSUE THREAD

**Issue by renxia** [fex-team/fis3-hook-commonjs#23]
如题，当前版本可能会存在如下警告：

> TypeError: Cannot read property 'substr' of undefined

https://github.com/fex-team/fis3-hook-commonjs/commit/dd99f1c14d3813f5e03e984d8d5335a598716694

这个提交只是屏蔽了该出错导致的编译中断，但问题原因在 `source-map`

`source-map` 官方已通过如下提交修复该问题

https://github.com/mozilla/source-map/pull/257/commits

所以应当升级一下版本以彻底解决

**Comment by 2betop** [comment]
求 pr

**Comment by 2betop** [comment]
+ fis3-hook-commonjs@0.1.28
