### ISSUE TITLE
现在 baseUrl 只支持一个字符串，有可能修改让它支持一个字符串数组么？

### ISSUE THREAD

**Issue by hanai** [fex-team/fis3-hook-commonjs#3]
依次遍历几个baseUrl，直到找的。

**Comment by oxUnd** [comment]
想法很不错

但

我为什么要把这个搞得这么复杂，请说你的例子或者原始需求，谢谢。

**Comment by hanai** [comment]
之前用 `fis` 做的时候 page 在一个目录下 `/page`，每个 page 对应的 module 在另一个目录下 `/modules`，常用的依赖比如 `jquery` 在 `/deps`下，所以配置像这样的

``` js
fis.hook('commonjs', {
    paths: {
        jquery: '/deps/jquery/jquery',
        moment: '/deps/moment/moment',
        lodash: '/deps/lodash/lodash',
        immutable: '/deps/immutable/immutable.min'
    },
    baseUrl: '/modules'
});
```

后来用了 `fis3` 和 `react` 了， 想把目录结构改成这样的，
![files-x](https://cloud.githubusercontent.com/assets/1222115/9625423/92229ffe-5188-11e5-9139-eac2649ed1a2.png)
然而目前只能设置单个baseUrl，就会导致必须要一次改完所有页面，而不能每改完一个页面都可以`release` 整个项目，且能够平稳过渡。

**Comment by oxUnd** [comment]
看样子你就是为了用_短路径_是吧？

还有别的你想解决的问题吗？对于_短路径_，我的想法是，能不用就不用。

相对路径、绝对路径（相对于项目根目录）+ domain，完美解决一切路径、url相关问题。

**Comment by 2betop** [comment]
@hanai  你是不是所有的引用 components 目录下面的 组件都是通过文件夹名字引用的？

如果是这样，我觉得我小改下原来支持 fis 组件生态的插件，就能满足你的需求。不确定是否正确。你先本地安装下 `npm install fis3-hook-components` 看看是否生效？记住是本地安装，不是全局安装，安装到你的项目目录下面。

**Comment by hanai** [comment]
用了相对路径，问题解决了。
