### ISSUE TITLE
lookup 的顺序的问题

### ISSUE THREAD

**Issue by GilbertSun** [fex-team/fis3-hook-commonjs#7]
lookup.js 里 查找的顺序是这样的

``` javascript
[
    tryNoExtLookUp,
    tryFisIdLookUp,
    tryPathsLookUp,
    tryPackagesLookUp,
    tryFolderLookUp,
    tryBaseUrlLookUp,
    tryRootLookUp
 ]
```

我遇见了这样一个问题

我通过 bower 安装了 react，react 的包结构是这样的

```
react
  |- react.js
  |- react-dom.js
  |- react-with-addons.js
```

在 react-dom.js 中

有这样一行依赖

``` javascript
require('react');
```

但是我们团队是将`react-with-addons.js`当做 react 的

也就是说，我们在插件的配置中加入了react 的 path

``` javascript
{
    paths: {
        'react': '/bower_components/react/react-with-addons.js',
        'react-dom': '/bower_components/react/react-dom.js'
    }
}
```

我们在项目中的文件引的时候是没问题的，会自动替换为`react-with-addons`, 但是包自身的 react-dom里面的那个依赖被替换为了包自身的`react.js`

现在我如果一个页面同时引入 react 和 react-dom 的话，会出现 react.js, react-dom.js, react-with-addons.js 全部被加载进来

这个问题的原因其实就是，查找的第一个就已经匹配上了包里的 react.js 就不会进行`tryPathsLookUp`的寻找了

我觉得，用户的配置权限应该要提高，查找顺序可能需要调整一下

``` javascript
[
    tryFisIdLookUp,
    tryPathsLookUp,
    tryPackagesLookUp,
    tryFolderLookUp,
    tryNoExtLookUp,
    tryBaseUrlLookUp,
    tryRootLookUp
 ]
```

**Comment by 2betop** [comment]
嗯，你说得很有道理，我会做响应的调整，调整完了我会在这里告诉你！

**Comment by 2betop** [comment]
`+ fis3-hook-commonjs@0.1.3`

**Comment by GilbertSun** [comment]
@2betop 效率真高
